// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.carlife.protobuf;

public final class CarlifeGyroscopeProto {
  private CarlifeGyroscopeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeGyroscope extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeGyroscope.newBuilder() to construct.
    private CarlifeGyroscope() {}
    
    private static final CarlifeGyroscope defaultInstance = new CarlifeGyroscope();
    public static CarlifeGyroscope getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeGyroscope getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.carlife.protobuf.CarlifeGyroscopeProto.internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.carlife.protobuf.CarlifeGyroscopeProto.internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_fieldAccessorTable;
    }
    
    // required int32 gyroType = 1;
    public static final int GYROTYPE_FIELD_NUMBER = 1;
    private boolean hasGyroType;
    private int gyroType_ = 0;
    public boolean hasGyroType() { return hasGyroType; }
    public int getGyroType() { return gyroType_; }
    
    // required double gyroX = 2;
    public static final int GYROX_FIELD_NUMBER = 2;
    private boolean hasGyroX;
    private double gyroX_ = 0D;
    public boolean hasGyroX() { return hasGyroX; }
    public double getGyroX() { return gyroX_; }
    
    // required double gyroy = 3;
    public static final int GYROY_FIELD_NUMBER = 3;
    private boolean hasGyroy;
    private double gyroy_ = 0D;
    public boolean hasGyroy() { return hasGyroy; }
    public double getGyroy() { return gyroy_; }
    
    // required double gyroZ = 4;
    public static final int GYROZ_FIELD_NUMBER = 4;
    private boolean hasGyroZ;
    private double gyroZ_ = 0D;
    public boolean hasGyroZ() { return hasGyroZ; }
    public double getGyroZ() { return gyroZ_; }
    
    // optional uint64 timeStamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private boolean hasTimeStamp;
    private long timeStamp_ = 0L;
    public boolean hasTimeStamp() { return hasTimeStamp; }
    public long getTimeStamp() { return timeStamp_; }
    
    public final boolean isInitialized() {
      if (!hasGyroType) return false;
      if (!hasGyroX) return false;
      if (!hasGyroy) return false;
      if (!hasGyroZ) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasGyroType()) {
        output.writeInt32(1, getGyroType());
      }
      if (hasGyroX()) {
        output.writeDouble(2, getGyroX());
      }
      if (hasGyroy()) {
        output.writeDouble(3, getGyroy());
      }
      if (hasGyroZ()) {
        output.writeDouble(4, getGyroZ());
      }
      if (hasTimeStamp()) {
        output.writeUInt64(5, getTimeStamp());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGyroType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getGyroType());
      }
      if (hasGyroX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, getGyroX());
      }
      if (hasGyroy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getGyroy());
      }
      if (hasGyroZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, getGyroZ());
      }
      if (hasTimeStamp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, getTimeStamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope result;
      
      // Construct using com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope();
        return builder;
      }
      
      protected com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.getDescriptor();
      }
      
      public com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope getDefaultInstanceForType() {
        return com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope) {
          return mergeFrom((com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope other) {
        if (other == com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.getDefaultInstance()) return this;
        if (other.hasGyroType()) {
          setGyroType(other.getGyroType());
        }
        if (other.hasGyroX()) {
          setGyroX(other.getGyroX());
        }
        if (other.hasGyroy()) {
          setGyroy(other.getGyroy());
        }
        if (other.hasGyroZ()) {
          setGyroZ(other.getGyroZ());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setGyroType(input.readInt32());
              break;
            }
            case 17: {
              setGyroX(input.readDouble());
              break;
            }
            case 25: {
              setGyroy(input.readDouble());
              break;
            }
            case 33: {
              setGyroZ(input.readDouble());
              break;
            }
            case 40: {
              setTimeStamp(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required int32 gyroType = 1;
      public boolean hasGyroType() {
        return result.hasGyroType();
      }
      public int getGyroType() {
        return result.getGyroType();
      }
      public Builder setGyroType(int value) {
        result.hasGyroType = true;
        result.gyroType_ = value;
        return this;
      }
      public Builder clearGyroType() {
        result.hasGyroType = false;
        result.gyroType_ = 0;
        return this;
      }
      
      // required double gyroX = 2;
      public boolean hasGyroX() {
        return result.hasGyroX();
      }
      public double getGyroX() {
        return result.getGyroX();
      }
      public Builder setGyroX(double value) {
        result.hasGyroX = true;
        result.gyroX_ = value;
        return this;
      }
      public Builder clearGyroX() {
        result.hasGyroX = false;
        result.gyroX_ = 0D;
        return this;
      }
      
      // required double gyroy = 3;
      public boolean hasGyroy() {
        return result.hasGyroy();
      }
      public double getGyroy() {
        return result.getGyroy();
      }
      public Builder setGyroy(double value) {
        result.hasGyroy = true;
        result.gyroy_ = value;
        return this;
      }
      public Builder clearGyroy() {
        result.hasGyroy = false;
        result.gyroy_ = 0D;
        return this;
      }
      
      // required double gyroZ = 4;
      public boolean hasGyroZ() {
        return result.hasGyroZ();
      }
      public double getGyroZ() {
        return result.getGyroZ();
      }
      public Builder setGyroZ(double value) {
        result.hasGyroZ = true;
        result.gyroZ_ = value;
        return this;
      }
      public Builder clearGyroZ() {
        result.hasGyroZ = false;
        result.gyroZ_ = 0D;
        return this;
      }
      
      // optional uint64 timeStamp = 5;
      public boolean hasTimeStamp() {
        return result.hasTimeStamp();
      }
      public long getTimeStamp() {
        return result.getTimeStamp();
      }
      public Builder setTimeStamp(long value) {
        result.hasTimeStamp = true;
        result.timeStamp_ = value;
        return this;
      }
      public Builder clearTimeStamp() {
        result.hasTimeStamp = false;
        result.timeStamp_ = 0L;
        return this;
      }
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeGyroscopeProto.getDescriptor();
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeGyroscopeProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CarlifeGyroscopeProto.proto\022\032com.baidu" +
      ".carlife.protobuf\"d\n\020CarlifeGyroscope\022\020\n" +
      "\010gyroType\030\001 \002(\005\022\r\n\005gyroX\030\002 \002(\001\022\r\n\005gyroy\030" +
      "\003 \002(\001\022\r\n\005gyroZ\030\004 \002(\001\022\021\n\ttimeStamp\030\005 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeGyroscope_descriptor,
              new java.lang.String[] { "GyroType", "GyroX", "Gyroy", "GyroZ", "TimeStamp", },
              com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.class,
              com.baidu.carlife.protobuf.CarlifeGyroscopeProto.CarlifeGyroscope.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
