// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.carlife.protobuf;

public final class CarlifeSubscribeMobileCarLifeInfoProto {
  private CarlifeSubscribeMobileCarLifeInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeSubscribeMobileCarLifeInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeSubscribeMobileCarLifeInfo.newBuilder() to construct.
    private CarlifeSubscribeMobileCarLifeInfo() {}
    
    private static final CarlifeSubscribeMobileCarLifeInfo defaultInstance = new CarlifeSubscribeMobileCarLifeInfo();
    public static CarlifeSubscribeMobileCarLifeInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeSubscribeMobileCarLifeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_fieldAccessorTable;
    }
    
    // required int32 moduleID = 1;
    public static final int MODULEID_FIELD_NUMBER = 1;
    private boolean hasModuleID;
    private int moduleID_ = 0;
    public boolean hasModuleID() { return hasModuleID; }
    public int getModuleID() { return moduleID_; }
    
    // optional bool supportFlag = 2;
    public static final int SUPPORTFLAG_FIELD_NUMBER = 2;
    private boolean hasSupportFlag;
    private boolean supportFlag_ = false;
    public boolean hasSupportFlag() { return hasSupportFlag; }
    public boolean getSupportFlag() { return supportFlag_; }
    
    // optional int32 frequency = 3;
    public static final int FREQUENCY_FIELD_NUMBER = 3;
    private boolean hasFrequency;
    private int frequency_ = 0;
    public boolean hasFrequency() { return hasFrequency; }
    public int getFrequency() { return frequency_; }
    
    public final boolean isInitialized() {
      if (!hasModuleID) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasModuleID()) {
        output.writeInt32(1, getModuleID());
      }
      if (hasSupportFlag()) {
        output.writeBool(2, getSupportFlag());
      }
      if (hasFrequency()) {
        output.writeInt32(3, getFrequency());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasModuleID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getModuleID());
      }
      if (hasSupportFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getSupportFlag());
      }
      if (hasFrequency()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getFrequency());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo result;
      
      // Construct using com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo();
        return builder;
      }
      
      protected com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.getDescriptor();
      }
      
      public com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo getDefaultInstanceForType() {
        return com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo) {
          return mergeFrom((com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo other) {
        if (other == com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.getDefaultInstance()) return this;
        if (other.hasModuleID()) {
          setModuleID(other.getModuleID());
        }
        if (other.hasSupportFlag()) {
          setSupportFlag(other.getSupportFlag());
        }
        if (other.hasFrequency()) {
          setFrequency(other.getFrequency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setModuleID(input.readInt32());
              break;
            }
            case 16: {
              setSupportFlag(input.readBool());
              break;
            }
            case 24: {
              setFrequency(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 moduleID = 1;
      public boolean hasModuleID() {
        return result.hasModuleID();
      }
      public int getModuleID() {
        return result.getModuleID();
      }
      public Builder setModuleID(int value) {
        result.hasModuleID = true;
        result.moduleID_ = value;
        return this;
      }
      public Builder clearModuleID() {
        result.hasModuleID = false;
        result.moduleID_ = 0;
        return this;
      }
      
      // optional bool supportFlag = 2;
      public boolean hasSupportFlag() {
        return result.hasSupportFlag();
      }
      public boolean getSupportFlag() {
        return result.getSupportFlag();
      }
      public Builder setSupportFlag(boolean value) {
        result.hasSupportFlag = true;
        result.supportFlag_ = value;
        return this;
      }
      public Builder clearSupportFlag() {
        result.hasSupportFlag = false;
        result.supportFlag_ = false;
        return this;
      }
      
      // optional int32 frequency = 3;
      public boolean hasFrequency() {
        return result.hasFrequency();
      }
      public int getFrequency() {
        return result.getFrequency();
      }
      public Builder setFrequency(int value) {
        result.hasFrequency = true;
        result.frequency_ = value;
        return this;
      }
      public Builder clearFrequency() {
        result.hasFrequency = false;
        result.frequency_ = 0;
        return this;
      }
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.getDescriptor();
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,CarlifeSubscribeMobileCarLifeInfoProto" +
      ".proto\022\032com.baidu.carlife.protobuf\"]\n!Ca" +
      "rlifeSubscribeMobileCarLifeInfo\022\020\n\010modul" +
      "eID\030\001 \002(\005\022\023\n\013supportFlag\030\002 \001(\010\022\021\n\tfreque" +
      "ncy\030\003 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeSubscribeMobileCarLifeInfo_descriptor,
              new java.lang.String[] { "ModuleID", "SupportFlag", "Frequency", },
              com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.class,
              com.baidu.carlife.protobuf.CarlifeSubscribeMobileCarLifeInfoProto.CarlifeSubscribeMobileCarLifeInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
