/*
 * Copyright (C) 2016 Baidu, Inc. All Rights Reserved.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.carlife.protobuf;

public final class CarlifeVehicleInfoProto {
  private CarlifeVehicleInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeVehicleInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeVehicleInfo.newBuilder() to construct.
    private CarlifeVehicleInfo() {}
    
    private static final CarlifeVehicleInfo defaultInstance = new CarlifeVehicleInfo();
    public static CarlifeVehicleInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeVehicleInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CarlifeVehicleInfoProto.internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CarlifeVehicleInfoProto.internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_fieldAccessorTable;
    }
    
    // required int32 moduleID = 1;
    public static final int MODULEID_FIELD_NUMBER = 1;
    private boolean hasModuleID;
    private int moduleID_ = 0;
    public boolean hasModuleID() { return hasModuleID; }
    public int getModuleID() { return moduleID_; }
    
    // optional int32 flag = 2;
    public static final int FLAG_FIELD_NUMBER = 2;
    private boolean hasFlag;
    private int flag_ = 0;
    public boolean hasFlag() { return hasFlag; }
    public int getFlag() { return flag_; }
    
    // optional int32 frequency = 3;
    public static final int FREQUENCY_FIELD_NUMBER = 3;
    private boolean hasFrequency;
    private int frequency_ = 0;
    public boolean hasFrequency() { return hasFrequency; }
    public int getFrequency() { return frequency_; }
    
    public final boolean isInitialized() {
      if (!hasModuleID) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasModuleID()) {
        output.writeInt32(1, getModuleID());
      }
      if (hasFlag()) {
        output.writeInt32(2, getFlag());
      }
      if (hasFrequency()) {
        output.writeInt32(3, getFrequency());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasModuleID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getModuleID());
      }
      if (hasFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getFlag());
      }
      if (hasFrequency()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getFrequency());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static CarlifeVehicleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CarlifeVehicleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static CarlifeVehicleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static CarlifeVehicleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CarlifeVehicleInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private CarlifeVehicleInfo result;
      
      // Construct using com.baidu.carlife.protobuf.CarlifeVehicleInfoProto.CarlifeVehicleInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new CarlifeVehicleInfo();
        return builder;
      }
      
      protected CarlifeVehicleInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new CarlifeVehicleInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CarlifeVehicleInfo.getDescriptor();
      }
      
      public CarlifeVehicleInfo getDefaultInstanceForType() {
        return CarlifeVehicleInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public CarlifeVehicleInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private CarlifeVehicleInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public CarlifeVehicleInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        CarlifeVehicleInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CarlifeVehicleInfo) {
          return mergeFrom((CarlifeVehicleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(CarlifeVehicleInfo other) {
        if (other == CarlifeVehicleInfo.getDefaultInstance()) return this;
        if (other.hasModuleID()) {
          setModuleID(other.getModuleID());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasFrequency()) {
          setFrequency(other.getFrequency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setModuleID(input.readInt32());
              break;
            }
            case 16: {
              setFlag(input.readInt32());
              break;
            }
            case 24: {
              setFrequency(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 moduleID = 1;
      public boolean hasModuleID() {
        return result.hasModuleID();
      }
      public int getModuleID() {
        return result.getModuleID();
      }
      public Builder setModuleID(int value) {
        result.hasModuleID = true;
        result.moduleID_ = value;
        return this;
      }
      public Builder clearModuleID() {
        result.hasModuleID = false;
        result.moduleID_ = 0;
        return this;
      }
      
      // optional int32 flag = 2;
      public boolean hasFlag() {
        return result.hasFlag();
      }
      public int getFlag() {
        return result.getFlag();
      }
      public Builder setFlag(int value) {
        result.hasFlag = true;
        result.flag_ = value;
        return this;
      }
      public Builder clearFlag() {
        result.hasFlag = false;
        result.flag_ = 0;
        return this;
      }
      
      // optional int32 frequency = 3;
      public boolean hasFrequency() {
        return result.hasFrequency();
      }
      public int getFrequency() {
        return result.getFrequency();
      }
      public Builder setFrequency(int value) {
        result.hasFrequency = true;
        result.frequency_ = value;
        return this;
      }
      public Builder clearFrequency() {
        result.hasFrequency = false;
        result.frequency_ = 0;
        return this;
      }
    }
    
    static {
      CarlifeVehicleInfoProto.getDescriptor();
    }
    
    static {
      CarlifeVehicleInfoProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\035CarlifeVehicleInfoProto.proto\022\032com.bai" +
      "du.carlife.protobuf\"G\n\022CarlifeVehicleInf" +
      "o\022\020\n\010moduleID\030\001 \002(\005\022\014\n\004flag\030\002 \001(\005\022\021\n\tfre" +
      "quency\030\003 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeVehicleInfo_descriptor,
              new String[] { "ModuleID", "Flag", "Frequency", },
              CarlifeVehicleInfo.class,
              CarlifeVehicleInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
