// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.baidu.carlife.protobuf;

public final class CarlifeCallRecordsProto {
  private CarlifeCallRecordsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CarlifeCallRecords extends
      com.google.protobuf.GeneratedMessage {
    // Use CarlifeCallRecords.newBuilder() to construct.
    private CarlifeCallRecords() {}
    
    private static final CarlifeCallRecords defaultInstance = new CarlifeCallRecords();
    public static CarlifeCallRecords getDefaultInstance() {
      return defaultInstance;
    }
    
    public CarlifeCallRecords getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baidu.carlife.protobuf.CarlifeCallRecordsProto.internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baidu.carlife.protobuf.CarlifeCallRecordsProto.internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_fieldAccessorTable;
    }
    
    public enum CallRecordsType
        implements com.google.protobuf.ProtocolMessageEnum {
      DEFAULT_TYPE(0, 0),
      INCOMING_TYPE(1, 1),
      OUTGOING_TYPE(2, 2),
      MISSED_TYPE(3, 3),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static CallRecordsType valueOf(int value) {
        switch (value) {
          case 0: return DEFAULT_TYPE;
          case 1: return INCOMING_TYPE;
          case 2: return OUTGOING_TYPE;
          case 3: return MISSED_TYPE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<CallRecordsType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CallRecordsType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CallRecordsType>() {
              public CallRecordsType findValueByNumber(int number) {
                return CallRecordsType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final CallRecordsType[] VALUES = {
        DEFAULT_TYPE, INCOMING_TYPE, OUTGOING_TYPE, MISSED_TYPE, 
      };
      public static CallRecordsType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private CallRecordsType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.baidu.carlife.protobuf.CarlifeCallRecordsProto.getDescriptor();
      }
    }
    
    // required int32 cid = 1;
    public static final int CID_FIELD_NUMBER = 1;
    private boolean hasCid;
    private int cid_ = 0;
    public boolean hasCid() { return hasCid; }
    public int getCid() { return cid_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required string number = 3;
    public static final int NUMBER_FIELD_NUMBER = 3;
    private boolean hasNumber;
    private java.lang.String number_ = "";
    public boolean hasNumber() { return hasNumber; }
    public java.lang.String getNumber() { return number_; }
    
    // required string duration = 4;
    public static final int DURATION_FIELD_NUMBER = 4;
    private boolean hasDuration;
    private java.lang.String duration_ = "";
    public boolean hasDuration() { return hasDuration; }
    public java.lang.String getDuration() { return duration_; }
    
    // required string time = 5;
    public static final int TIME_FIELD_NUMBER = 5;
    private boolean hasTime;
    private java.lang.String time_ = "";
    public boolean hasTime() { return hasTime; }
    public java.lang.String getTime() { return time_; }
    
    // required .com.baidu.carlife.protobuf.CarlifeCallRecords.CallRecordsType type = 6 [default = DEFAULT_TYPE];
    public static final int TYPE_FIELD_NUMBER = 6;
    private boolean hasType;
    private com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType type_ = com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType.DEFAULT_TYPE;
    public boolean hasType() { return hasType; }
    public com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType getType() { return type_; }
    
    public final boolean isInitialized() {
      if (!hasCid) return false;
      if (!hasName) return false;
      if (!hasNumber) return false;
      if (!hasDuration) return false;
      if (!hasTime) return false;
      if (!hasType) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasCid()) {
        output.writeInt32(1, getCid());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasNumber()) {
        output.writeString(3, getNumber());
      }
      if (hasDuration()) {
        output.writeString(4, getDuration());
      }
      if (hasTime()) {
        output.writeString(5, getTime());
      }
      if (hasType()) {
        output.writeEnum(6, getType().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getCid());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNumber());
      }
      if (hasDuration()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDuration());
      }
      if (hasTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getTime());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, getType().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords result;
      
      // Construct using com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords();
        return builder;
      }
      
      protected com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.getDescriptor();
      }
      
      public com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords getDefaultInstanceForType() {
        return com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords) {
          return mergeFrom((com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords other) {
        if (other == com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCid(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              setNumber(input.readString());
              break;
            }
            case 34: {
              setDuration(input.readString());
              break;
            }
            case 42: {
              setTime(input.readString());
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType value = com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                setType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // required int32 cid = 1;
      public boolean hasCid() {
        return result.hasCid();
      }
      public int getCid() {
        return result.getCid();
      }
      public Builder setCid(int value) {
        result.hasCid = true;
        result.cid_ = value;
        return this;
      }
      public Builder clearCid() {
        result.hasCid = false;
        result.cid_ = 0;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required string number = 3;
      public boolean hasNumber() {
        return result.hasNumber();
      }
      public java.lang.String getNumber() {
        return result.getNumber();
      }
      public Builder setNumber(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNumber = true;
        result.number_ = value;
        return this;
      }
      public Builder clearNumber() {
        result.hasNumber = false;
        result.number_ = getDefaultInstance().getNumber();
        return this;
      }
      
      // required string duration = 4;
      public boolean hasDuration() {
        return result.hasDuration();
      }
      public java.lang.String getDuration() {
        return result.getDuration();
      }
      public Builder setDuration(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDuration = true;
        result.duration_ = value;
        return this;
      }
      public Builder clearDuration() {
        result.hasDuration = false;
        result.duration_ = getDefaultInstance().getDuration();
        return this;
      }
      
      // required string time = 5;
      public boolean hasTime() {
        return result.hasTime();
      }
      public java.lang.String getTime() {
        return result.getTime();
      }
      public Builder setTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTime = true;
        result.time_ = value;
        return this;
      }
      public Builder clearTime() {
        result.hasTime = false;
        result.time_ = getDefaultInstance().getTime();
        return this;
      }
      
      // required .com.baidu.carlife.protobuf.CarlifeCallRecords.CallRecordsType type = 6 [default = DEFAULT_TYPE];
      public boolean hasType() {
        return result.hasType();
      }
      public com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType getType() {
        return result.getType();
      }
      public Builder setType(com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.CallRecordsType.DEFAULT_TYPE;
        return this;
      }
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeCallRecordsProto.getDescriptor();
    }
    
    static {
      com.baidu.carlife.protobuf.CarlifeCallRecordsProto.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035CarlifeCallRecordsProto.proto\022\032com.bai" +
      "du.carlife.protobuf\"\227\002\n\022CarlifeCallRecor" +
      "ds\022\013\n\003cid\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\016\n\006number\030" +
      "\003 \002(\t\022\020\n\010duration\030\004 \002(\t\022\014\n\004time\030\005 \002(\t\022Z\n" +
      "\004type\030\006 \002(\0162>.com.baidu.carlife.protobuf" +
      ".CarlifeCallRecords.CallRecordsType:\014DEF" +
      "AULT_TYPE\"Z\n\017CallRecordsType\022\020\n\014DEFAULT_" +
      "TYPE\020\000\022\021\n\rINCOMING_TYPE\020\001\022\021\n\rOUTGOING_TY" +
      "PE\020\002\022\017\n\013MISSED_TYPE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_baidu_carlife_protobuf_CarlifeCallRecords_descriptor,
              new java.lang.String[] { "Cid", "Name", "Number", "Duration", "Time", "Type", },
              com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.class,
              com.baidu.carlife.protobuf.CarlifeCallRecordsProto.CarlifeCallRecords.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
